{
  ShipNavPanel - export the planet/moon hierarchy for the nav panel.

  Writes one line per PNDT (planet) record:

      formID,systemID,parentPlanetID,planetID

  taken from GNAM "Galaxy Data". A planet carries parent 0; a moon carries the
  Planet ID of the planet it orbits (Earth = 0,0,3 and Luna = 0,3,11 in Sol).

  WHY THIS EXISTS: the runtime PNDT object does not hold GNAM. Its records are
  0x58 bytes, laid out back to back, and every word is spoken for -
  surfaceTree, a float, temperature, density, orbital angle, resource speed and
  the form id. So the hierarchy has to come from the ESM, where it plainly is.

  HOW TO RUN
    1. Open xEdit with Starfield.esm loaded (the base master is enough).
    2. Apply Script -> ShipNavPanel Export Bodies. Selection does not matter;
       it walks the loaded files itself.
    3. It writes ShipNavPanelBodies.txt beside xEdit. Copy that to
         <game>\Data\SFSE\Plugins\ShipNavPanelBodies.txt

  If the element paths below do not match your xEdit build, the log says so and
  names the elements it did find under GNAM - adjust kPathSystem/kParent/kPlanet
  to suit.
}
unit ShipNavPanelExportBodies;

const
  kOutput  = 'ShipNavPanelBodies.txt';
  kPathSys = 'GNAM\Star System ID';
  kPathPar = 'GNAM\Parent Planet ID';
  kPathPla = 'GNAM\Planet ID';

var
  gLines:     TStringList;
  gExported:  Integer;
  gSkipped:   Integer;
  gReported:  Boolean;

function Initialize: Integer;
begin
  gLines := TStringList.Create;
  gLines.Add('# ShipNavPanel body table - generated by tools/ExportBodies.pas');
  gLines.Add('# formID,systemID,parentPlanetID,planetID');
  gLines.Add('# A planet has parentPlanetID 0; a moon carries its planet''s planetID.');
  gExported := 0;
  gSkipped  := 0;
  gReported := False;
  Result := 0;
end;

{ Dumps GNAM's children once, so a path mismatch is diagnosable rather than
  just an empty file. }
procedure ReportGnamShape(e: IInterface);
var
  gnam: IInterface;
  i:    Integer;
begin
  if gReported then Exit;
  gReported := True;

  gnam := ElementByPath(e, 'GNAM');
  if not Assigned(gnam) then begin
    AddMessage('ShipNavPanel: no GNAM on ' + Name(e) + ' - is this really a PNDT?');
    Exit;
  end;

  AddMessage('ShipNavPanel: GNAM of ' + Name(e) + ' contains:');
  for i := 0 to ElementCount(gnam) - 1 do
    AddMessage('    "' + Name(ElementByIndex(gnam, i)) + '"');
  AddMessage('ShipNavPanel: if the names above differ from Star System ID / '
           + 'Parent Planet ID / Planet ID, edit kPathSys/kPathPar/kPathPla.');
end;

function Process(e: IInterface): Integer;
var
  sSys, sPar, sPla: string;
begin
  Result := 0;
  if Signature(e) <> 'PNDT' then Exit;

  { Winning override only, so a patch that edits a planet is respected and the
    same body is not written twice. }
  if not IsWinningOverride(e) then Exit;

  sSys := GetElementEditValues(e, kPathSys);
  sPar := GetElementEditValues(e, kPathPar);
  sPla := GetElementEditValues(e, kPathPla);

  if (sPla = '') then begin
    Inc(gSkipped);
    ReportGnamShape(e);
    Exit;
  end;

  if sSys = '' then sSys := '0';
  if sPar = '' then sPar := '0';

  gLines.Add(IntToHex(FormID(e), 8) + ',' + sSys + ',' + sPar + ',' + sPla);
  Inc(gExported);
end;

function Finalize: Integer;
begin
  gLines.SaveToFile(kOutput);
  AddMessage('ShipNavPanel: wrote ' + IntToStr(gExported) + ' bodies to ' + kOutput);
  if gSkipped > 0 then
    AddMessage('ShipNavPanel: skipped ' + IntToStr(gSkipped)
             + ' PNDT records with no readable Planet ID');
  AddMessage('ShipNavPanel: copy it to <game>\Data\SFSE\Plugins\' + kOutput);
  gLines.Free;
  Result := 0;
end;

end.
